language: python

sudo: required

python:
  - "3.5"

branches:
  only:
    - master
  
install: 
  - pip install -r requirements.txt
  - cd module
  - python setup.py install
  - cd ..
  
script:
  - pytest
